version: '3.8'

services:
  infer:
    build: .
    ports:
      - "9082:9082"
    environment:
      - HOST=0.0.0.0
      - PORT=9082
      - MODEL_PATH=models/latest
      - DATA_PATH=data/serving_train_finetuned.csv
      - MODEL_URI=/app/AutogluonModels/ag-20250909_084146
    volumes:
      - ./app:/app/app
      - ./models:/app/models
      - ./data:/app/data
      - /Users/coldbrew_groom/Documents/order-platform-mlops/order-platform-msa-train-pipeline/AutogluonModels:/app/AutogluonModels
    command: >
      sh -c "uv run uvicorn app.main:app --host 0.0.0.0 --port 9082 --reload"


